
plugins:
  - babel

env:
  node: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:react/recommended'

rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  no-param-reassign: 0

settings:
  import/resolver:
    - node
    - webpack:
      - config: webpack.config.js
  react:
    version: 'detect'